Travis debugging

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -16,15 +16,15 @@ git config --global user.email "dotfiles@demo.com"
 # bootstrap the mighty
 echo 'running ./script/bootstrap...'
 ./script/bootstrap
-echo 'done running ./script/bootstrap...'
-
-# load zshrc and check if antibody is working
-echo 'sourcing ~/.zshrc...'
-source ~/.zshrc || {
-  echo "error sourcing ~/.zshrc" >&2
-  exit 1
-}
-echo 'done sourcing ~/.zshrc'
+# echo 'done running ./script/bootstrap...'
+#
+# # load zshrc and check if antibody is working
+# echo 'sourcing ~/.zshrc...'
+# source ~/.zshrc || {
+#   echo "error sourcing ~/.zshrc" >&2
+#   exit 1
+# }
+# echo 'done sourcing ~/.zshrc'
 
 test $(antibody list | wc -l) -gt 5 || {
   echo "expecting 5+ bundles loaded" >&2
