More logging

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -20,7 +20,10 @@ echo 'done running ./script/bootstrap...'
 
 # load zshrc and check if antibody is working
 echo 'sourcing ~/.zshrc...'
-source ~/.zshrc
+source ~/.zshrc || {
+  echo "error sourcing ~/.zshrc" >&2
+  exit 1
+}
 echo 'done sourcing ~/.zshrc'
 
 test $(antibody list | wc -l) -gt 5 || {
